# Docker is only used for testing and the resulting images should not be published
docker:
  publish: false
npm:
  platforms:
    - name: linux
      os: alpine
      architecture: x86_64
      node_versions:
        - '14'
