version: '2.1'

services:
  postgres:
    image: balena/open-balena-db:4.1.0
    restart: always
    networks:
      - internal
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U docker']
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: balena/balena-redis:0.0.3
    command: [sh, -c, "redis-server /usr/local/etc/redis/redis.conf --save ''"]
    restart: always
    networks:
      - internal
    ports:
      - '6379:6379'

networks:
  internal: {}
