###########################################################
# Runtime
###########################################################

FROM node:12

WORKDIR /usr/src/jellyfish

COPY package.json package-lock.json ./
ARG NPM_TOKEN
RUN echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc && \
    npm i && rm -f ~/.npmrc

COPY . ./

CMD /bin/bash -c "make test-integration"