version: '2.1'

services:
  postgres:
    image: balena/open-balena-db:v5.0.3
    restart: always
    networks:
      - internal
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U docker']
      interval: 5s
      timeout: 5s
      retries: 5
    command: ['postgres', '-c', 'fsync=off', '-c', 'synchronous_commit=off', '-c', 'full_page_writes=off']
  redis:
    image: balena/balena-redis:v0.0.4
    command: [sh, -c, "redis-server /usr/local/etc/redis/redis.conf --save ''"]
    restart: always
    networks:
      - internal
    ports:
      - '6379:6379'

networks:
  internal: {}
